sudo: true

language: java

#install:
#- sudo apt-get update
#- sudo apt-get install google-chrome-stable

jdk:
  - oraclejdk8

os:
- linux
#- osx

script: ant build

#Nearly there, check current travis output when running ant test: http://pastebin.com/9M4YUR0Q
#script: ant test


#before_install:
# - cd java